[package]
name = "composer-list"
version = "0.1.0"
authors = ["osanshouo <53166653+osanshouo@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "0.6"
wasm-bindgen = "0.2"
lazy_static = "1.4"
